-- ============================================================================
-- SEED 02 — schemas & objects (run against the SOURCE RDS `app` database)
-- ============================================================================
-- Deliberately exercises the object types a real migration must carry: schemas owned by non-admin
-- roles, an identity sequence, a standalone sequence, foreign keys, a CHECK constraint, a
-- range-partitioned table, a view, a materialized view, and a trigger + function. Objects are
-- created under SET ROLE so they are owned by the per-service roles (not the admin) — the ownership
-- the migration must reproduce on the target.

CREATE SCHEMA IF NOT EXISTS sales   AUTHORIZATION svc_sales;
CREATE SCHEMA IF NOT EXISTS billing AUTHORIZATION svc_billing;

-- --- sales (owned by svc_sales) --------------------------------------------
SET ROLE svc_sales;

CREATE TABLE IF NOT EXISTS sales.customer (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      citext UNIQUE NOT NULL,
  full_name  text   NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sales.orders (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES sales.customer (id),
  total_cents bigint NOT NULL CHECK (total_cents >= 0),
  status      text   NOT NULL DEFAULT 'pending',
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Trigger + function to maintain updated_at (a routine + trigger for the migration to carry).
CREATE OR REPLACE FUNCTION sales.set_updated_at() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_customer_updated ON sales.customer;
CREATE TRIGGER trg_customer_updated
  BEFORE UPDATE ON sales.customer
  FOR EACH ROW EXECUTE FUNCTION sales.set_updated_at();

RESET ROLE;

-- --- billing (owned by svc_billing) ----------------------------------------
SET ROLE svc_billing;

-- Range-partitioned table (by issue date) with two partitions + a standalone sequence and a
-- pgcrypto-generated uuid default.
CREATE TABLE IF NOT EXISTS billing.invoice (
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  order_id     bigint NOT NULL,
  amount_cents bigint NOT NULL,
  issued_at    date   NOT NULL,
  token        uuid   NOT NULL DEFAULT gen_random_uuid(),
  PRIMARY KEY (id, issued_at)
) PARTITION BY RANGE (issued_at);

CREATE TABLE IF NOT EXISTS billing.invoice_2024 PARTITION OF billing.invoice
  FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
CREATE TABLE IF NOT EXISTS billing.invoice_2025 PARTITION OF billing.invoice
  FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

CREATE SEQUENCE IF NOT EXISTS billing.invoice_no_seq;

-- A view and a materialized view over the partitioned table.
CREATE OR REPLACE VIEW billing.invoice_totals AS
  SELECT issued_at, count(*) AS n, sum(amount_cents) AS total_cents
  FROM billing.invoice
  GROUP BY issued_at;

CREATE MATERIALIZED VIEW IF NOT EXISTS billing.invoice_monthly AS
  SELECT date_trunc('month', issued_at)::date AS month,
         count(*)                              AS n,
         sum(amount_cents)                     AS total_cents
  FROM billing.invoice
  GROUP BY 1
  WITH NO DATA;

RESET ROLE;
